//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.18 at 05:32:54 PM CET 
//


package org.synyx.minos.core.remoting.rest.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.joda.time.DateTime;
import org.w3._2001.xmlschema.Adapter1;


/**
 * <p>Java class for abstract-entity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="abstract-entity">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.synyx.de/minos/core/rest}identifyable">
 *       &lt;sequence>
 *         &lt;element name="created-by" type="{http://schemas.synyx.de/minos/core/rest}identifyable" minOccurs="0"/>
 *         &lt;element name="modified-by" type="{http://schemas.synyx.de/minos/core/rest}identifyable" minOccurs="0"/>
 *         &lt;element name="link" type="{http://schemas.synyx.de/minos/core/rest}link" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="created" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="last-modified" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "abstract-entity", propOrder = {
    "createdBy",
    "modifiedBy",
    "link"
})
public class AbstractEntityDto
    extends IdentifyableDto
{

    @XmlElement(name = "created-by")
    protected IdentifyableDto createdBy;
    @XmlElement(name = "modified-by")
    protected IdentifyableDto modifiedBy;
    protected List<LinkDto> link;
    @XmlAttribute
    @XmlJavaTypeAdapter(Adapter1 .class)
    protected DateTime created;
    @XmlAttribute(name = "last-modified")
    @XmlJavaTypeAdapter(Adapter1 .class)
    protected DateTime lastModified;

    /**
     * Gets the value of the createdBy property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifyableDto }
     *     
     */
    public IdentifyableDto getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifyableDto }
     *     
     */
    public void setCreatedBy(IdentifyableDto value) {
        this.createdBy = value;
    }

    /**
     * Gets the value of the modifiedBy property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifyableDto }
     *     
     */
    public IdentifyableDto getModifiedBy() {
        return modifiedBy;
    }

    /**
     * Sets the value of the modifiedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifyableDto }
     *     
     */
    public void setModifiedBy(IdentifyableDto value) {
        this.modifiedBy = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the link property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LinkDto }
     * 
     * 
     */
    public List<LinkDto> getLink() {
        if (link == null) {
            link = new ArrayList<LinkDto>();
        }
        return this.link;
    }

    /**
     * Gets the value of the created property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public DateTime getCreated() {
        return created;
    }

    /**
     * Sets the value of the created property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreated(DateTime value) {
        this.created = value;
    }

    /**
     * Gets the value of the lastModified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public DateTime getLastModified() {
        return lastModified;
    }

    /**
     * Sets the value of the lastModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastModified(DateTime value) {
        this.lastModified = value;
    }

}
