//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.0.2-b01-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2008.10.23 at 04:35:32 PM CEST
//

package org.synyx.minos.im.remoting.rest.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.joda.time.DateTime;
import org.synyx.minos.core.remoting.rest.dto.IdentifyableDto;



/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://www.synyx.de/minos/im}identifyable&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;sender&quot; type=&quot;{http://www.synyx.de/minos/im}identifyable&quot;/&gt;
 *         &lt;element name=&quot;receipient&quot; type=&quot;{http://www.synyx.de/minos/im}identifyable&quot;/&gt;
 *         &lt;element name=&quot;text&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name=&quot;read&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}boolean&quot; default=&quot;false&quot; /&gt;
 *       &lt;attribute name=&quot;send-date&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}dateTime&quot; /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "sender", "receipient", "text" })
@XmlRootElement(name = "instant-message")
public class InstantMessageDto extends IdentifyableDto {

    @XmlElement(required = true)
    protected IdentifyableDto sender;
    @XmlElement(required = true)
    protected IdentifyableDto receipient;
    @XmlElement(required = true)
    protected String text;
    @XmlAttribute
    protected Boolean read;
    @XmlAttribute(name = "send-date")
    @XmlJavaTypeAdapter(Adapter1.class)
    protected DateTime sendDate;


    /**
     * Gets the value of the sender property.
     * 
     * @return possible object is {@link IdentifyableDto }
     */
    public IdentifyableDto getSender() {

        return sender;
    }


    /**
     * Sets the value of the sender property.
     * 
     * @param value allowed object is {@link IdentifyableDto }
     */
    public void setSender(IdentifyableDto value) {

        this.sender = value;
    }


    /**
     * Gets the value of the receipient property.
     * 
     * @return possible object is {@link IdentifyableDto }
     */
    public IdentifyableDto getReceipient() {

        return receipient;
    }


    /**
     * Sets the value of the receipient property.
     * 
     * @param value allowed object is {@link IdentifyableDto }
     */
    public void setReceipient(IdentifyableDto value) {

        this.receipient = value;
    }


    /**
     * Gets the value of the text property.
     * 
     * @return possible object is {@link String }
     */
    public String getText() {

        return text;
    }


    /**
     * Sets the value of the text property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setText(String value) {

        this.text = value;
    }


    /**
     * Gets the value of the read property.
     * 
     * @return possible object is {@link Boolean }
     */
    public boolean isRead() {

        if (read == null) {
            return false;
        } else {
            return read;
        }
    }


    /**
     * Sets the value of the read property.
     * 
     * @param value allowed object is {@link Boolean }
     */
    public void setRead(Boolean value) {

        this.read = value;
    }


    /**
     * Gets the value of the sendDate property.
     * 
     * @return possible object is {@link String }
     */
    public DateTime getSendDate() {

        return sendDate;
    }


    /**
     * Sets the value of the sendDate property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setSendDate(DateTime value) {

        this.sendDate = value;
    }

}
