//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.23 at 04:35:32 PM CEST 
//


package org.synyx.minos.im.remoting.rest.dto;

import javax.xml.bind.annotation.adapters.XmlAdapter;

import org.joda.time.DateTime;

public class Adapter1
    extends XmlAdapter<String, DateTime>
{


    public DateTime unmarshal(String value) {
        return (org.synyx.minos.support.remoting.JaxbDateConverter.parseDate(value));
    }

    public String marshal(DateTime value) {
        return (org.synyx.minos.support.remoting.JaxbDateConverter.printDate(value));
    }

}
