//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.23 at 04:35:32 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.synyx.de/minos/im", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.synyx.minos.im.remoting.rest.dto;
