//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.18 at 05:32:54 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.synyx.de/minos/core/rest", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.synyx.minos.core.remoting.rest.dto;

