//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2008.12.18 at 05:32:54 PM CET
//

package org.w3._2001.xmlschema;

import org.joda.time.DateTime;

import javax.xml.bind.annotation.adapters.XmlAdapter;


public class Adapter1 extends XmlAdapter<String, DateTime> {

    @Override
    public DateTime unmarshal(String value) {

        return (org.synyx.minos.support.remoting.JaxbDateConverter.parseDate(value));
    }


    @Override
    public String marshal(DateTime value) {

        return (org.synyx.minos.support.remoting.JaxbDateConverter.printDate(value));
    }
}
